github.com:
    users:
        rishibhargawa:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: rishibhargawa
