[general]
live_config_reload=true

[window]
opacity=0.99
padding={x=5,y=5}
decorations = "None"
blur=true

[scrolling]
history=10000
multiplier=5

[font]
normal={family="Fira Mono",style="Regular"}
size=8

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
