[general]
live_config_reload=true

[window]
opacity=0.8
padding={x=2,y=2}
decorations = "None"
blur=true

[scrolling]
history=10000
multiplier=5

[font]
normal={family="JetBrainsMono Nerd Font Mono",style="Regular"}
size=10

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
